demoWebOrderFood/Controllers/UserController.cs
using BotDetect.Web.Mvc;
using demoWebOrderFood.Common;
using demoWebOrderFood.Models;
using Model.Dao;
using Model1.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace demoWebOrderFood.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Login()
        {

            return View();
        }

        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {

                var dao = new Userdao();
                var result = dao.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.ID;
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    return Redirect("/");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tên đăng nhập hoặc mật khẩu không đúng");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khóa");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Tên đăng nhập hoặc mật khẩu không đúng");
                }
                else
                {
                    ModelState.AddModelError("", "Tên đăng nhập hoặc mật khẩu không đúng");
                }
            }
            
            return View(model);
        }

        [HttpPost]
        [CaptchaValidationActionFilter("captchacode", "registercaptcha", "Wrong Captcha!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new Userdao();
                if (dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (dao.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else if (dao.isEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email nhập sai định dạng.");
                }
                else
                {
                    var user = new User();
                    user.UserName = model.UserName;
                    user.Name = model.Name;
                    user.Password = Encryptor.MD5Hash(model.Password);
                    user.Email = model.Email;
                    user.CreateDate = DateTime.Now;
                    user.Status = true;
                    
                    var result = dao.Insert(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                        ModelState.Clear();
                        MvcCaptcha.ResetCaptcha("captchacode");
                    }
                    else
                    {
                        ViewBag.Success = "Đăng ký không thành công";
                        model.Password = "";
                        model.ConfirmPassword = "";
                        MvcCaptcha.ResetCaptcha("captchacode");
                    }

                }
            }
            return View(model);
        }

        
    }
}

demoWebOrderFood/Controllers/UserProfileController.cs
using demoWebOrderFood.Common;
using Model.Dao;
using Model1.Dao;
using Model1.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace demoWebOrderFood.Controllers
{
    
    public class UserProfileController : Controller
    {
      

        // GET: UserProfile

        public ActionResult Index()
        {
            
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session == null)
                return Redirect("/");
            else
            {
                var username = session.UserName;
                var model = new Userdao().profileUser(username);
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var dao = new Userdao();
            var user = dao.ViewDetail(id);
            return View(user);
        }
        [HttpPost]
        public ActionResult Edit(User model)
        {
            if (ModelState.IsValid)
            {
                var dao = new Userdao();

                var result = dao.Update(model);
                if (result)
                {
                    return Redirect("/user-profile");
                }
                else
                {
                    ModelState.AddModelError("", "update successfully!!!");
                }
            }
            return View(model);
        }


        public ActionResult HistoryOrder(int page = 1, int pageSize = 8)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            var username = session.UserName;
            var dao = new ProductDao();
            var model = dao.ListAll(username, page, pageSize);      
            return View(model);
        }
    }
}

demoWebOrderFood/Views/UserProfile/HistoryOrder.cshtml
@model PagedList.IPagedList<Model1.EF.Product>
@using PagedList.Mvc;
@{
    ViewBag.Title = "HOrder";
    Layout = "~/Views/Shared/Trade.cshtml";
    var ListNewProduct = (List<Model1.EF.Product>)ViewBag.NewProducts;
    var category = (Model1.EF.ProductCategory)ViewBag.Category;
}

    <style>
        .posted__user {
            margin-top: 3rem !important;
            margin-bottom: 5rem !important;
        }
        .editUser {
            position: absolute;
            top: 188px;
            left: 51%;
        }

        .editUser .hvt {
            padding: 17px 0;
        }

        .modal {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: 999;
            display: none;
        }

        .modal__overFlow {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            overflow-y: hidden;
            padding-right: 15px;
        }

        .hvt input {
            width: 600px;
        }

        .btn__disable {
            display: none;
        }

        .btn__formUpdate {
            display: flex;
            justify-content: flex-end;
            margin-top: 5px;
        }

        .button {
            padding: 10px;
            margin: 0 5px;
            border-radius: 5px;
        }
            .product__title a {
                text-decoration: none;
                color: #000;
                font-size: 18px;
            }
        </style>
    <div class="grid wide sm-gutter posted__user">
        <input class="btn__primary button btn__cancel" type="button" onclick="window.location.replace('/user-profile')" value="Back Profile" />
        @if (Model.Count() > 0)
        {
            <div class="row">
                <div class="col l-10">
                    <div class="product">
                        <div class="row">

                            @foreach (var item in Model)
                            {
                                var url = "/chi-tiet/" + item.MetaTile + "-" + item.ID;
                                <div class="col l-2-4 c-6 mt-5">
                                    <article class="product__item wow fadeInUp" data-wow-delay="0.1s">


                                        <a href="@url" class="product-hot-sales-wrapper">
                                            <div class="product-hot-sales-item">
                                                <div class="product-hot-sales-img" style="background-image: url(@item.Image); padding-top: 100%;background-size: cover">
                                                </div>
                                                <div class="product-hot-sales-name"> @item.Name</div>
                                                <div class="product-hot-sales-price">
                                                    @item.CreateBy
                                                    <span class="posted-on th-block">
                                                        <a href="" rel="bookmark">
                                                            <time class="entry-date published">
                                                                @Html.FormatValue(item.CreateDate, "{0:dd/MM/yyyy}")
                                                            </time>
                                                        </a>
                                                    </span>
                                                </div>
                                            </div>
                                        </a>



                                        @*<a href="@url" class="product__item-link" style="background-image: url(@item.Image); padding-top: 100%; background-size: cover; background-repeat: non-repeat">

                                        </a>
                                        <header class="product__header">
                                            <h2 class="product__title">
                                                <a href="@url" rel="bookmark">@item.Name</a>
                                            </h2>
                                        </header>
                                        <footer class="product-footer">
                                            <div class="product__post">
                                                <span class="byline th-block th-uppercase">
                                                    By
                                                    <a href="" class="url fn n">@item.CreateBy</a>
                                                </span>
                                                <span class="posted-on th-block">
                                                    <a href="" rel="bookmark">
                                                        <time class="entry-date published">
                                                            @Html.FormatValue(item.CreateDate, "{0:dd/MM/yyyy}")
                                                        </time>
                                                    </a>
                                                </span>
                                            </div>
                                        </footer>*@
                                    </article>
                                </div>
                            }
                        </div>

                    </div>
                </div>

            </div>
            <div class="pagination-list">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))

            </div>
        }
        else
        {
            <div class="noProduct" style="position: relative; top: 50%; left: 37%">
                <img src="~/Assets/client/images/no-cart-edit.png" style="width: 320px; height: 200px " />
                <h1 style=" font-size: 22px; color: #fff; text-align: center; margin: 20px 0; width: 300px">No products</h1>
            </div>
        }
    </div>
<br />

demoWebOrderFood/Views/UserProfile/Index.cshtml
@model Model1.EF.User
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Trade.cshtml";
}
<style>
    .main-body {
        margin: 5rem 0;
    }
    .editUser {
        position: absolute;
        top: 291px;
        left: 51%;
    }
        .editUser .hvt + .hvt {
            padding-top: 33px;
        }
    .modal {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 999;
        display: none;
        background-color: rgba(0,0,0,0.5);
    }
    .btn__editUser, .btn__postUser {
        padding: 4px 8px;
        font-size: 16px;
        border-radius: 5px;
    }
    a.btn__postUser{
        color: #000;
        text-decoration: none;
    }
    .modal__overFlow {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        overflow-y: hidden;
    }
    .hvt input {
        width: 600px;
     
    }
    .btn__disable{
        display: none;
    }
    .btn__formUpdate{
        display: flex;
        justify-content: flex-end;
        margin-top: 26px;
    }
   
    .button {
        padding: 10px;
        margin: 0 5px;
        border-radius: 5px;
    }
    .btn__logOut{
        display: none;
    }
    .btn__logOut a {
        color: #fff;
        font-size: 22px;
        text-decoration: none;
    }
</style>
<script>
    $('#img__user').on('click', function (e) {
        e.preventDefault();
        var finder = new CKFinder();
        finder.selectActionFunction = function (url) {
            $('#txtImage').val(url);
        };
        finder.popup();
    })
    var editor = CKEDITOR.replace('txtContent', {
        customConfig: '/Assets/Admin/js/plugins/ckeditor/config.js',
    });
</script>
<div class="main-body">

    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.UserName Profile</li>
        </ol>
    </nav>
    <!-- /Breadcrumb -->

    <div class="row gutters-sm">
        <div class="col-md-4 mb-3 content-img">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <a href="" id="img__user"> <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150"></a>
                        <div class="mt-3">
                            <h4>@Model.Name</h4>
                            <p class="text-secondary mb-1">@Html.FormatValue(Model.Email, "{0:dd/MM/yyyy}")</p>
                            <p class="text-muted font-size-sm">@Model.Address</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-8 content-info">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Name
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Email
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Mobile</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Phone
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            @Model.Address
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col sm-12">
                            <button onclick="document.getElementById('id02').style.display='block'" class=" btn__primary btn__editUser">Edit profile</button>
                        </div>
                        <br />
                        <!-- click edit -->
                        @*<div class="col sm-12">
                                <button class="btn btn__primary">Save</button>
                                <button class="btn btn__primary">Cancel</button>
                            </div>*@
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col sm-12">
                            <a href="/UserProfile/HistoryOrder" onclick="document.getElementById('id01').style.display='block'" class=" btn__primary btn__postUser">Posted</a>
                        </div>
                        <br />
                    </div>
                    <div class="modal"></div>
                </div>
            </div>


        </div>

    </div>
    <div class="btn__primary btn__receive btn__logOut" style="width: 150px; height: 50px; ">@Html.ActionLink("Logout", "Logout", "User")</div>
</div>

@using (Html.BeginForm("Edit", "UserProfile", FormMethod.Post))
{
    <div id="id02" class="modal">
        <form class="modal-content animate" action="Edit" method="post">
            <div class="imgcontainer">
                
                @*<img class="circle1" src="@Model.Anh" alt="" />*@
            </div>

            @Html.HiddenFor(model => model.ID)
        <div class="editUser">
            <div class="hvt">
                @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="hvt">
                @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @id = "input__email" } })

            </div>
            <div class="hvt">
                @Html.TextBoxFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })

            </div>
            <div class="hvt">
                @Html.TextBoxFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })

            </div>
            
            <div class="btn__formUpdate">
                <button type="submit" class="btn__primary button btn__update">Update</button>
                <input class="btn__primary button btn__cancel" type="button" onclick="window.location.replace('/user-profile')" value="Cancel" />
            </div>
            @*<div class="hvt">
            <label for="uname"><h3 class="Name">Ảnh</h3></label>
            <br />
            <input type="text"
                   value="@Model.Anh"
                   name="Image"
                   id="xFilePath"
                   class="imageCV"
                   style="width:44% !important"
                   required />
            <a id="SelectImage" onclick="BrowseServer()" style="position: relative;top: 25px" href="#">Chọn ảnh</a>
        </div>*@


        </div>
        
        </form>
    </div>
    <script>
        $(function () {
            $('.btn__editUser').click(function () {
                $('.btn__editUser').addClass('btn__disable');        
             
                $('body,html').addClass('modal__overFlow');
            })
            $('.btn__cancel').click(function () {
                $('.btn__editUser').removeClass('btn__disable');  
             
                $('body,html').removeClass('modal__overFlow');
            })
        })


    </script>
}